# This is a basic workflow to help you get started with Actions

name: Auto-Version On Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Modify version.h
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: version.h
          body: '#define VERSION "${{ github.ref }}"'
          overwrite: 'true'
          token: ${{ secrets.GITHUB_TOKEN }}
